In [1438]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Task 1: Creating new feature

# load csv

In [1439]:
data=pd.read_csv('amazon.csv')
df=pd.DataFrame(data)

In [1440]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [1441]:
df.shape

(1465, 16)

In [1442]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [1443]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 4.7 MB

In [1444]:
# Convert price columns to numeric
df['actual_price'] = (df['actual_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float))

df['discounted_price'] = (df['discounted_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float))

# Convert discount percentage to numeric
df['discount_percentage'] = (df['discount_percentage'].str.replace('%', '', regex=False).astype(float))

# Convert rating count to numeric
df['rating_count'] = (df['rating_count'].str.replace(',', '', regex=False))

df['rating'] = (df['rating'].str.replace('|', '0.0', regex=False))

In [1445]:
df['rating_count'].isnull().sum()
df['rating_count']=df['rating_count'].fillna(0)
df['rating_count']=df['rating_count'].astype('int32')

In [1446]:
df['rating'].value_counts()

rating
4.1    244
4.3    230
4.2    228
4.0    129
3.9    123
4.4    123
3.8     86
4.5     75
4       52
3.7     42
3.6     35
3.5     26
4.6     17
3.3     16
3.4     10
4.7      6
3.1      4
5.0      3
3.0      3
4.8      3
3.2      2
2.8      2
2.3      1
0.0      1
2        1
3        1
2.6      1
2.9      1
Name: count, dtype: int64

In [1447]:
df['rating'] = df['rating'].astype(float)

In [1448]:
df['rating_count'].dtype

dtype('int32')

In [1449]:
df['savings_amount'] = df['actual_price'] - df['discounted_price']

In [1450]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1465 non-null   float64
 7   rating_count         1465 non-null   int32
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
 16  savings_amount       1465 non-null   float64
dtypes: float64(5), int32(1), str(11)
memory usage: 4.6 MB

In [1451]:
df.sample(5)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,savings_amount
827,B09RKFBCV7,"Fire-Boltt Ninja Calling 1.69"" Bluetooth Calli...",Electronics|WearableTechnology|SmartWatches,1999.0,7999.0,75.0,4.2,31305,Fire-Boltt is India' No 1 Wearable Watch Brand...,"AGDI3CM73SM6W3GZTPAXJ23GNXUA,AF2WVFRQZPM6MC653...","siddhi kamat,Reshma Sagar,Mahima singh,Sayanta...","R2ATT3WQL0UB7P,R1VHI2ZGJSCFVO,R1UHC2M2KPN7W4,R...","Value for money Product,Watch start button,VAL...",I've been using the watch for a while now and ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Fire-Boltt-Bluetooth-Sma...,6000.0
504,B09W5XR9RT,Duracell USB C To Lightning Apple Certified (M...,Computers&Accessories|Accessories&Peripherals|...,970.0,1999.0,51.0,4.4,184,1.2M Tangle Free durable tough braiding sync &...,"AHZWJCVEIEI76H2VGMUSN5D735IQ,AH2DFUHFTG4CKQFVG...","Amazon Customer,Govind Gujarathi,Vihari,shalem...","R1Y30KU04V3QF4,RK3DSUGKIZT8Z,R3BIG7J6V2JZTU,R1...","Very good product.,Using as a spare cable in c...","Fast charging.,Cable seems to be of good quali...",https://m.media-amazon.com/images/I/4177nw8okb...,https://www.amazon.in/Duracell-Lightning-Certi...,1029.0
647,B09NR6G588,Boult Audio ZCharge Bluetooth Wireless in Ear ...,"Electronics|Headphones,Earbuds&Accessories|Hea...",1199.0,4999.0,76.0,3.8,14961,Note : If the size of the earbud tips does not...,"AESKYYTGWJ7VJASMOE6QQUDXSITQ,AH6RJFHNEDVIFN34S...","Kevin Nathan S,Subha,Jatin Raikwar,Sarvesh Yad...","R274KY6VMEYJ66,R28WM6HPG5V7YO,R3TAACQ304V0Q5,R...","Worst Customer Support , Most Regretted Purcha...",Update: Now after this review they have told m...,https://m.media-amazon.com/images/I/31-1GGUrjU...,https://www.amazon.in/Boult-Audio-Bluetooth-En...,3800.0
428,B08CF3D7QR,Portronics Konnect L POR-1081 Fast Charging 3A...,Computers&Accessories|Accessories&Peripherals|...,154.0,339.0,55.0,4.3,13391,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...","Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...","R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...",Good for fast charge but not for data transfer...,The cable is efficient in fast charging but in...,https://m.media-amazon.com/images/I/31dJ+lXJq3...,https://www.amazon.in/Portronics-POR-1081-Char...,185.0
706,B09Y5MP7C4,Noise Buds Vs104 Bluetooth Truly Wireless in E...,"Electronics|Headphones,Earbuds&Accessories|Hea...",1299.0,3499.0,63.0,3.9,12452,Up to 30-hour playtime: Get set for a day full...,"AHLPMR4VVPOQ2YOHBFOZ55D7OUVQ,AFXQR65B2ONAPVNIF...","Achint,Anish,bhomick bhaskar,Sumit,Des Raj,Ama...","R2XES5SVJG8YP1,R3ISE0B84H2FC4,R32PBSE5T01GP3,R...","BUDGET TWS,Does its job,Bhomick bhasker,Noise ...",HONEST REVIEW :-I got these buds in ₹895/- and...,https://m.media-amazon.com/images/I/31YW3+kpZQ...,https://www.amazon.in/Noise-Bluetooth-Wireless...,2200.0

# Task 2: Handing date feature and text feature

In [1452]:
# Length of product description (characters)
df['about_product_length'] = df['about_product'].astype(str).str.len()

# Number of words in product description
df['about_product_word_count'] = df['about_product'].astype(str).str.split().str.len()

# Length of review (characters)
df['review_length'] = df['review_content'].astype(str).str.len()

# Number of words in review
df['review_word_count'] = df['review_content'].astype(str).str.split().str.len()

In [1453]:
df[['product_name',
    'about_product_length',
    'about_product_word_count',
    'review_length',
    'review_word_count']].head()

,product_name,about_product_length,about_product_word_count,review_length,review_word_count
0,Wayona Nylon Braided USB to Lightning Fast Cha...,960,132,483,60
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,605,93,1186,201
2,Sounce Fast Phone Charging Cable & Data Sync U...,1091,168,271,13
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,699,109,443,77
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,574,95,2451,415

# PART 2 :Feature Encoding

# Task 3 : One-Hot Encoding

In [1454]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,...,review_id,review_title,review_content,img_link,product_link,savings_amount,about_product_length,about_product_word_count,review_length,review_word_count
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...",...,"R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,700.0,960,132,483,60
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,43994,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...",...,"RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,150.0,605,93,1186,201
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,7928,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...",...,"R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,1700.0,1091,168,271,13
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,94363,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...",...,"R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,370.0,699,109,443,77
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,16905,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...",...,"R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,245.0,574,95,2451,415

In [1455]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_id                1465 non-null   str
 1   product_name              1465 non-null   str
 2   category                  1465 non-null   str
 3   discounted_price          1465 non-null   float64
 4   actual_price              1465 non-null   float64
 5   discount_percentage       1465 non-null   float64
 6   rating                    1465 non-null   float64
 7   rating_count              1465 non-null   int32
 8   about_product             1465 non-null   str
 9   user_id                   1465 non-null   str
 10  user_name                 1465 non-null   str
 11  review_id                 1465 non-null   str
 12  review_title              1465 non-null   str
 13  review_content            1465 non-null   str
 14  img_link                  1465 non-null   str
 15  product_link              1465 non-null   str
 16  savings_amount            1465 non-null   float64
 17  about_product_length      1465 non-null   int64
 18  about_product_word_count  1465 non-null   int64
 19  review_length             1465 non-null   int64
 20  review_word_count         1465 non-null   int64
dtypes: float64(5), int32(1), int64(4), str(11)
memory usage: 4.7 MB

In [1456]:
df=df[['product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count','user_id', 'review_id',  'savings_amount','about_product_length', 'about_product_word_count', 'review_length','review_word_count']]

In [1457]:
# Price category
df['price_category'] = pd.cut(
    df['discounted_price'],
    bins=[0, 500, 2000, float('inf')],
    labels=['Budget', 'Mid-Range', 'Premium']
)

# Discount category
df['discount_category'] = pd.cut(
    df['discount_percentage'],
    bins=[0, 25, 50, 100],
    labels=['Low', 'Medium', 'High']
)

# Rating category
df['rating_category'] = pd.cut(
    df['rating'],
    bins=[0, 3.5, 4.2, 5],
    labels=['Average', 'Good', 'Excellent']
)

In [1458]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_name              1465 non-null   str
 1   category                  1465 non-null   str
 2   discounted_price          1465 non-null   float64
 3   actual_price              1465 non-null   float64
 4   discount_percentage       1465 non-null   float64
 5   rating                    1465 non-null   float64
 6   rating_count              1465 non-null   int32
 7   user_id                   1465 non-null   str
 8   review_id                 1465 non-null   str
 9   savings_amount            1465 non-null   float64
 10  about_product_length      1465 non-null   int64
 11  about_product_word_count  1465 non-null   int64
 12  review_length             1465 non-null   int64
 13  review_word_count         1465 non-null   int64
 14  price_category            1465 non-null   category
 15  discount_category         1416 non-null   category
 16  rating_category           1464 non-null   category
dtypes: category(3), float64(5), int32(1), int64(4), str(4)
memory usage: 935.9 KB

# Identify Categorical Columns

In [1459]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

/var/folders/q2/jg_sv82d5z79tj_05d1fbrzr0000gn/T/ipykernel_3585/3445425799.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object', 'category']).columns

In [1460]:
categorical_columns

Index(['product_name', 'category', 'user_id', 'review_id', 'price_category',
       'discount_category', 'rating_category'],
      dtype='str')

## One-Hot Encoding

In [1461]:
df_encoded = pd.get_dummies(
    pd,columns=['product_name', 'category','price_category', 'discount_category', 'rating_category'],dtype=int
)

In [1462]:
print(df_encoded)

   <module 'pandas' from '/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/pandas/__init__.py'>
0                                                  1

## Task 4: Column Transformer

## separate numerical feature

In [1463]:
numerical_columns = df.select_dtypes(include=['number']).columns.tolist()

In [1464]:
numerical_columns

['discounted_price',
 'actual_price',
 'discount_percentage',
 'rating',
 'rating_count',
 'savings_amount',
 'about_product_length',
 'about_product_word_count',
 'review_length',
 'review_word_count']

## separate categorical feature

In [1465]:
df=df[[ 'category', 'discounted_price', 'actual_price',
       'discount_percentage','rating', 'rating_count', 'savings_amount', 'about_product_length', 'about_product_word_count' , 
       'review_length', 'review_word_count', 'price_category', 'rating_category','discount_category']]

In [1466]:
df['about_product_length']=df['about_product_length'].astype('int32')
df['about_product_word_count']=df['about_product_word_count'].astype('int32')
df['review_length']=df['review_length'].astype('int32')
df['review_word_count']=df['review_word_count'].astype('int32')

In [1467]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

/var/folders/q2/jg_sv82d5z79tj_05d1fbrzr0000gn/T/ipykernel_3585/3803760702.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

In [1468]:
categorical_columns

['category', 'price_category', 'rating_category', 'discount_category']

In [1469]:
encode_cols = ['category', 'price_category', 'discount_category', 'rating_category']

In [1470]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()

In [1471]:
nominal_cat=one.fit_transform(df[encode_cols])

In [1472]:
nominal_cat

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5860 stored elements and shape (1465, 222)>

In [1473]:
df.head()

,category,discounted_price,actual_price,discount_percentage,rating,rating_count,savings_amount,about_product_length,about_product_word_count,review_length,review_word_count,price_category,rating_category,discount_category
0,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269,700.0,960,132,483,60,Budget,Good,High
1,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,43994,150.0,605,93,1186,201,Budget,Good,Medium
2,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,7928,1700.0,1091,168,271,13,Budget,Good,High
3,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,94363,370.0,699,109,443,77,Budget,Good,High
4,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,16905,245.0,574,95,2451,415,Budget,Good,High

In [1474]:
df.columns

Index(['category', 'discounted_price', 'actual_price', 'discount_percentage',
       'rating', 'rating_count', 'savings_amount', 'about_product_length',
       'about_product_word_count', 'review_length', 'review_word_count',
       'price_category', 'rating_category', 'discount_category'],
      dtype='str')

## Column Transformer

In [1475]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [1476]:
transformer = ColumnTransformer(transformers=[
        ('tr1', OrdinalEncoder(categories=[['Budget', 'Mid-Range', 'Premium']]), ['price_category']),
        ('tr2', OneHotEncoder(handle_unknown='ignore'), encode_cols)
    ],
    remainder='passthrough'
)

In [1477]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['Budget',
                                                             'Mid-Range',
                                                             'Premium']]),
                                 ['price_category']),
                                ('tr2', OneHotEncoder(handle_unknown='ignore'),
                                 ['category', 'price_category',
                                  'discount_category', 'rating_category'])])

In [1478]:
# Features
X = df.drop(columns=['rating'])

# Target
y = df['rating']

In [1479]:
X.columns

Index(['category', 'discounted_price', 'actual_price', 'discount_percentage',
       'rating_count', 'savings_amount', 'about_product_length',
       'about_product_word_count', 'review_length', 'review_word_count',
       'price_category', 'rating_category', 'discount_category'],
      dtype='str')

In [1480]:
X=transformer.fit_transform(X)

In [1481]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 19835 stored elements and shape (1465, 232)>

## LableEncoder

In [1482]:
l=LabelEncoder()
y=l.fit_transform(y)

In [1483]:
y

array([18, 16, 15, ..., 12, 16, 19], shape=(1465,))

## PART 3 - Feature scaling

## Task 5 : Standardization(StandardScaler)

# Step 1: Select Numerical Features

In [1484]:
from sklearn.preprocessing import StandardScaler

In [1485]:

numerical_cols = df.select_dtypes(include=['int32', 'float64']).columns

In [1486]:
numerical_cols

Index(['discounted_price', 'actual_price', 'discount_percentage', 'rating',
       'rating_count', 'savings_amount', 'about_product_length',
       'about_product_word_count', 'review_length', 'review_word_count'],
      dtype='str')

## Step 2: Apply StandardScaler

In [1487]:
scaler = StandardScaler()
X=df[numerical_cols]
X= scaler.fit_transform(X)

In [1488]:
X

array([[-0.39273074, -0.39977415,  0.75402906, ...,  0.24603446,
        -0.49983719, -0.57116638],
       [-0.42154116, -0.46876432, -0.21691117, ..., -0.2888251 ,
        -0.11418146, -0.12566514],
       [-0.42154116, -0.32618464,  1.95614555, ...,  0.73975097,
        -0.61613735, -0.71966679],
       ...,
       [-0.13055596, -0.21754813, -0.91043991, ..., -1.00197117,
        -0.28204868, -0.2836443 ],
       [-0.24867867, -0.32701252, -1.00291041, ..., -0.30253944,
        -0.55195283, -0.59960262],
       [-0.03778643, -0.16143613, -1.18785141, ..., -0.8648277 ,
         0.03448526,  0.0544311 ]], shape=(1465, 10))

## Step 3: Verify Mean and Standard Deviation

In [1489]:
print(X.mean().round(2))
print(X.std().round(2))

0.0
1.0

Mean ≈ 0: StandardScaler subtracts the mean from each numerical feature, centering the data around zero.

Standard Deviation ≈ 1: It divides each feature by its standard deviation, so all numerical features have a similar scale.

## Task 6 :Normalization (MinMaxScalar)

## Step 1: Apply MinMaxScaler

In [1490]:
df[numerical_cols]

,discounted_price,actual_price,discount_percentage,rating,rating_count,savings_amount,about_product_length,about_product_word_count,review_length,review_word_count
0,399.0,1099.0,64.0,4.2,24269,700.0,960,132,483,60
1,199.0,349.0,43.0,4.0,43994,150.0,605,93,1186,201
2,199.0,1899.0,90.0,3.9,7928,1700.0,1091,168,271,13
3,329.0,699.0,53.0,4.2,94363,370.0,699,109,443,77
4,154.0,399.0,61.0,4.2,16905,245.0,574,95,2451,415
...,...,...,...,...,...,...,...,...,...,...
1460,379.0,919.0,59.0,4.0,1090,540.0,423,71,479,77
1461,2280.0,3045.0,25.0,4.1,4118,765.0,28,6,1036,179
1462,2219.0,3080.0,28.0,3.6,468,861.0,297,41,880,151
1463,1399.0,1890.0,26.0,4.0,8031,491.0,528,92,388,51
1464,2863.0,3690.0,22.0,4.3,6987,827.0,391,51,1457,258

In [1491]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

# Numerical columns

# Fit and transform
X_minmax = minmax.fit_transform(df[numerical_cols])

# Convert to DataFrame
import pandas as pd

X_minmax = pd.DataFrame(X_minmax, columns=numerical_cols)

X_minmax.head()

,discounted_price,actual_price,discount_percentage,rating,rating_count,savings_amount,about_product_length,about_product_word_count,review_length,review_word_count
0,0.004618,0.007579,0.680851,0.84,0.056840,0.011307,0.361605,0.323457,0.022511,0.016537
1,0.002053,0.002216,0.457447,0.80,0.103037,0.002423,0.227187,0.227160,0.060552,0.064124
2,0.002053,0.013299,0.957447,0.78,0.018568,0.027459,0.411208,0.412346,0.011039,0.000675
3,0.003720,0.004719,0.563830,0.84,0.221005,0.005976,0.262779,0.266667,0.020346,0.022275
4,0.001475,0.002574,0.648936,0.84,0.039593,0.003957,0.215449,0.232099,0.129004,0.136348

## Step 2: Show values are between 0 and 1

In [1492]:
print(X_minmax.min())

discounted_price            0.0
actual_price                0.0
discount_percentage         0.0
rating                      0.0
rating_count                0.0
savings_amount              0.0
about_product_length        0.0
about_product_word_count    0.0
review_length               0.0
review_word_count           0.0
dtype: float64

In [1493]:
print(X_minmax.max())

discounted_price            1.0
actual_price                1.0
discount_percentage         1.0
rating                      1.0
rating_count                1.0
savings_amount              1.0
about_product_length        1.0
about_product_word_count    1.0
review_length               1.0
review_word_count           1.0
dtype: float64

Step 3:
StandardScaler transforms the data so that each numerical feature has a mean close to 0 and a standard deviation close to 1. The scaled values can be negative or positive.

MinMaxScaler rescales the data so that the minimum value becomes 0 and the maximum value becomes 1. All other values fall between 0 and 1.

# PART 4 - Building ML Pipeline

In [1494]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# 1. Separate features and target first
X = df.drop(columns=['rating'])
y = df['rating']

# 2. Extract column names directly from X (prevents 'rating' from being included)
numerical_cols = X.select_dtypes(
    include=['int32', 'int64', 'float64']
).columns.tolist()
categorical_columns = X.select_dtypes(
    include=['object', 'category']
).columns.tolist()

# 3. Create individual pipelines
num_pipeline = Pipeline(steps=[('scaler', StandardScaler())])

cat_pipeline = Pipeline(
    steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))]
)

# 4. Combine in ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, numerical_cols),
        ('cat', cat_pipeline, categorical_columns),
    ]
)

# 5. Fit and transform features
X_processed = preprocessor.fit_transform(X)

/var/folders/q2/jg_sv82d5z79tj_05d1fbrzr0000gn/T/ipykernel_3585/2374283748.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(

In [1495]:
X_processed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 19045 stored elements and shape (1465, 231)>

## Task 8 : Full Scikit-learn Pipeline

In [1496]:
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# 1. Separate features (X) and continuous target (y)
X = df.drop(columns=['rating'])
y = df['rating']

# Define numerical and categorical columns from X
numerical_cols = X.select_dtypes(
    include=['int32', 'int64', 'float64']
).columns.tolist()
categorical_columns = X.select_dtypes(
    include=['object', 'category']
).columns.tolist()

# 2. Build the ColumnTransformer (Encoding for categorical + Scaling for numerical)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns),
    ]
)

# 3. Create the full scikit-learn Pipeline (Preprocessing -> Model)
full_pipeline = Pipeline(
    steps=[('preprocessor', preprocessor), ('model', LinearRegression())]
)

# 4. Split data into train-test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

/var/folders/q2/jg_sv82d5z79tj_05d1fbrzr0000gn/T/ipykernel_3585/3152568170.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(

In [1497]:
X_train.shape

(1172, 13)

In [1498]:
X_test.shape

(293, 13)

In [1499]:
y_train.shape

(1172,)

In [1500]:
y_test.shape

(293,)

In [1501]:
# 5. Fit the pipeline on training data
full_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['discounted_price',
                                                   'actual_price',
                                                   'discount_percentage',
                                                   'rating_count',
                                                   'savings_amount',
                                                   'about_product_length',
                                                   'about_product_word_count',
                                                   'review_length',
                                                   'review_word_count']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['category', 'price_category',
                                                   'rating_category',
                                                   'discount_category'])])),
                ('model', LinearRegression())])

In [1502]:
# 6. Make predictions on test data
y_pred = full_pipeline.predict(X_test)

In [1508]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [1506]:
mean_absolute_error(y_test, y_pred)

0.1253279961081855

In [1509]:
mean_squared_error(y_test, y_pred)

0.02851265400624146